### ISSUE TITLE
Chromatic aberration and scaling of color channels

### ISSUE THREAD

**Issue by basilevh** [yoonsikp/chromate#7]
I was wondering what your logic is behind selecting the resizing factors ? Currently you have red = 1, green = 1 + 0.018 * strength, and blue = 1 + 0.044 * strength.  However, most literature suggests that the green channel should have the largest outward deviation, surpassing blue (which actually blends with red and becomes magenta instead, i.e. think of blue ~= 1 in this context).  Are your choices made for aesthetic purposes or is there a realistic explanation behind it ?
Thank you.

**Comment by yoonsikp** [comment]
@basilevh 

Hello, first of all, thank you for the message, my late reply is because I didn't actually get a notification for this (pls fix github).

I'm basing it on the optics of a simple lens, which should always have chromatic aberration in the order of the spectra, i.e. high to low wavelength. The reason behind chromatic aberration is due the changes in refraction, which is based on the wavelength, so I am assuming that would be the order it would be in.
